{"name": "test_d", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_out.TestOut object at 0x0000029555FA5370>\n\n    def test_d(self):\n        print('这是 test_out_b')\n>       assert False\nE       assert False\n\ntest_out.py:7: AssertionError"}, "start": 1595911390265, "stop": 1595911390266, "uuid": "94b66f93-67a6-4b23-bab3-8392055d4ac4", "historyId": "8588fcd33b4abe20c16d2dd7205c3956", "testCaseId": "47578f56620549fbc795c2de2cb76188", "fullName": "scripts.test_out.TestOut#test_d", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_out"}, {"name": "subSuite", "value": "TestOut"}, {"name": "host", "value": "DESKTOP-KHUJN4N"}, {"name": "thread", "value": "13732-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_out"}]}